### ISSUE TITLE
Drawing 8-9 pixels under the cursor

### ISSUE THREAD

**Issue by devildefu** [olekolek1000/MPS#2]
MPS draws 8-9 pixels under the cursor, after moving to workspace 1 (i3) and to workspace 2 it is already drawing correctly

OS: Manjaro Linux 17.1.6 Hakoila
WM: i3
Resolution: 1280x1024

Please, correct this error.

**Comment by devildefu** [comment]
However, you can do less and more, I managed from 3 to about 15 and more

**Comment by oo8dev** [comment]
Some drivers do not work correctly in Fullscreen mode.
This problem can be solved by exiting from the Fullscreen mode (F4 key)

**Comment by oo8dev** [comment]
Fixed.
