### ISSUE TITLE
Propozycje

### ISSUE THREAD

**Issue by RunePowered** [olekolek1000/MPS#4]
Proponuje dodać button nowy projekt, żeby nie trzeba było gasić programu.

**Comment by oo8dev** [comment]
Jak na razie rozwiązaniem jest kliknięcie klawisza "End" na klawiaturze. Jest to oczywiście tymczasowe.

**Comment by oo8dev** [comment]
Dzięki za pomysł, szczerze to nie wiem jak mogłem o tym zapomnieć.
