### ISSUE TITLE
Bugi

### ISSUE THREAD

**Issue by RunePowered** [olekolek1000/MPS#5]
*Kółko od pickowania kolorów nie zawsze jest w miejscu myszki co utrudnia wybór kolorów.

**Comment by oo8dev** [comment]
Spróbuj jednorazowo rozszerzyć okno, problem występuje tylko przy niektórych sterownikach/systemach. To powinno rozwiązać problem. Sam problem złych koordynatów myszy wciąż jest rozwiązywany.

**Comment by oo8dev** [comment]
![obraz](https://user-images.githubusercontent.com/29149078/38460610-803d5858-3abd-11e8-8f0f-15e47e632aa4.png)
Problem jest o tyle bardziej złożony, że nie można go odwzorować na moim sprzęcie.

**Comment by oo8dev** [comment]
Problem naprawiony.
